/* eslint-disable */
// THIS FILE IS GENERATED by codegen/plugin.js — do not edit by hand.
import { parse } from "graphql";
import type { TypedDocument } from "./graphql";

export type StocktakeLineFragment = {
  __typename: "StocktakeLineNode";
  stocktakeId: string;
  batch: string | null;
  itemId: string;
  itemName: string;
  id: string;
  expiryDate: string | null;
  manufactureDate: string | null;
  packSize: number | null;
  snapshotNumberOfPacks: number;
  countedNumberOfPacks: number | null;
  sellPricePerPack: number | null;
  costPricePerPack: number | null;
  comment: string | null;
  volumePerPack: number;
  donorId: string | null;
  donorName: string | null;
  manufacturer: NameRowFragment | null;
  location: {
  __typename: "LocationNode";
  id: string;
  name: string;
  code: string;
  onHold: boolean;
  locationType: {
  id: string;
  name: string;
} | null;
} | null;
  stockLine: {
  __typename: "StockLineNode";
  id: string;
} | null;
  item: {
  __typename: "ItemNode";
  id: string;
  code: string;
  name: string;
  unitName: string | null;
  isVaccine: boolean;
  doses: number;
  defaultPackSize: number;
  restrictedLocationTypeId: string | null;
  itemStoreProperties: {
  defaultSellPricePerPack: number;
} | null;
};
  itemVariantId: string | null;
  vvmStatus: VVMStatusFragment | null;
  itemVariant: {
  __typename: "ItemVariantNode";
  id: string;
  packagingVariants: Array<{
  __typename: "PackagingVariantNode";
  id: string;
  packSize: number | null;
  volumePerUnit: number | null;
}>;
} | null;
  reasonOption: {
  reason: string;
  type: "POSITIVE_INVENTORY_ADJUSTMENT" | "NEGATIVE_INVENTORY_ADJUSTMENT" | "OPEN_VIAL_WASTAGE" | "RETURN_REASON" | "REQUISITION_LINE_VARIANCE" | "CLOSED_VIAL_WASTAGE" | "SHIPMENT_VARIANCE";
  isActive: boolean;
  id: string;
} | null;
  campaign: {
  id: string;
  name: string;
} | null;
  program: {
  id: string;
  name: string;
} | null;
};

export type NameRowFragment = {
  code: string;
  id: string;
  isCustomer: boolean;
  isSupplier: boolean;
  isOnHold: boolean;
  name: string;
  store: {
  id: string;
  code: string;
  isDisabled: boolean;
} | null;
};

export type VVMStatusFragment = {
  __typename: "VvmstatusNode";
  description: string;
  id: string;
  priority: number;
  reasonId: string | null;
  unusable: boolean;
};

export type StocktakeLinesVariables = {
  stocktakeId: string;
  storeId: string;
  page?: {
    first?: number | null;
    offset?: number | null;
  } | null;
  sort?: Array<{
    key: "itemCode" | "itemName" | "batch" | "expiryDate" | "packSize" | "locationCode" | "snapshotNumberOfPacks" | "countedNumberOfPacks" | "reasonOption";
    desc?: boolean | null;
  }> | null;
  filter?: {
    id?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    stocktakeId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    locationId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    itemCodeOrName?: {
    equalTo?: string | null;
    like?: string | null;
  } | null;
    itemId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
    stockLineId?: {
    equalTo?: string | null;
    equalAny?: Array<string> | null;
    notEqualTo?: string | null;
    equalAnyOrNull?: Array<string> | null;
    notEqualAll?: Array<string> | null;
  } | null;
  } | null;
};

export type StocktakeLinesResult = {
  stocktakeLines: ({
  __typename: "StocktakeLineConnector";
  totalCount: number;
  nodes: Array<StocktakeLineFragment>;
});
};

export const StocktakeLines = {
  document: parse("query stocktakeLines($stocktakeId: String!, $storeId: String!, $page: PaginationInput, $sort: [StocktakeLineSortInput!], $filter: StocktakeLineFilterInput) {\n  stocktakeLines(\n    stocktakeId: $stocktakeId\n    storeId: $storeId\n    page: $page\n    sort: $sort\n    filter: $filter\n  ) {\n    ... on StocktakeLineConnector {\n      __typename\n      totalCount\n      nodes {\n        ...StocktakeLine\n      }\n    }\n  }\n}\n\nfragment StocktakeLine on StocktakeLineNode {\n  __typename\n  stocktakeId\n  batch\n  itemId\n  itemName\n  id\n  expiryDate\n  manufactureDate\n  packSize\n  snapshotNumberOfPacks\n  countedNumberOfPacks\n  sellPricePerPack\n  costPricePerPack\n  comment\n  volumePerPack\n  donorId\n  donorName\n  manufacturer(storeId: $storeId) {\n    ...NameRow\n  }\n  location {\n    __typename\n    id\n    name\n    code\n    onHold\n    locationType {\n      id\n      name\n    }\n  }\n  stockLine {\n    __typename\n    id\n  }\n  item {\n    __typename\n    id\n    code\n    name\n    unitName\n    isVaccine\n    doses\n    defaultPackSize\n    restrictedLocationTypeId\n    itemStoreProperties(storeId: $storeId) {\n      defaultSellPricePerPack\n    }\n  }\n  itemVariantId\n  vvmStatus {\n    ...VVMStatus\n  }\n  itemVariant {\n    __typename\n    id\n    packagingVariants {\n      __typename\n      id\n      packSize\n      volumePerUnit\n    }\n  }\n  reasonOption {\n    reason\n    type\n    isActive\n    id\n  }\n  campaign {\n    id\n    name\n  }\n  program {\n    id\n    name\n  }\n}\n\nfragment NameRow on NameNode {\n  code\n  id\n  isCustomer\n  isSupplier\n  isOnHold\n  name\n  store {\n    id\n    code\n    isDisabled\n  }\n}\n\nfragment VVMStatus on VvmstatusNode {\n  __typename\n  description\n  id\n  priority\n  reasonId\n  unusable\n}"),
} as TypedDocument<StocktakeLinesResult, StocktakeLinesVariables>;
